title: Kevin Blicharski
url: "https://kblicharski.github.io"
baseurl: 
home: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: ""
footer_text: "&copy; 2020 Kevin Blicharski"

favicon: true
favicon_location: "assets/favicon"

avatar_url: "assets/img/me.jpeg"
github_icon: "assets/img/mark-github.svg"
gitlab_icon: "assets/img/mark-gitlab.svg"
linkedin_icon: "assets/img/mark-linkedin.png"
devpost_icon: "assets/img/mark-devpost.svg"
stackoverflow_icon: "assets/img/mark-stackoverflow.svg"
twitter_icon: "assets/img/mark-twitter.svg"
uiowa_logo: "assets/img/uiowa-logo.png"
hackiowa_logo: "assets/img/hackiowa-logo.png"
acm_logo: "assets/img/acm-logo.svg"
ieee_logo: "assets/img/ieee-logo.svg"

github_url: "https://github.com/kblicharski/"
gitlab_url: "https://gitlab.com/kblicharski"
linkedin_url: "https://www.linkedin.com/in/kblicharski/"
devpost_url: "https://devpost.com/kblicharski"
stackoverflow_url: "https://stackoverflow.com/users/8261793/kevin-blicharski"
twitter_url: "https://twitter.com/kevinblicharski"

hackathon_faq: "https://mlh.io/faq#what-is-a-hackathon"

sass:
    style: compressed
    sass_dir: _sass

nav:
 # - name: "Education"
 #   link: "education"
 # - name: "Experience"
 #   link: "experience"
 - name: "Projects"
   link: "projects"
 - name: "Resume"
   link: "resume.pdf"

defaults:
 - scope:
     path: "assets/img"
   values:
     image: true
